# Site settings
author: Anya Brun
title: Anya Brun
header-img: img/home-bg.png
email: tsbrun@icloud.com
copyright_name: Anya Brun
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tsbrun

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
